### ISSUE TITLE
Make sure that data-cataloging is transparent to users

### ISSUE THREAD

**Issue by rtapella** [unity-sds/ui-ux#3]
Automated data-ingestion should be possible to observe, track, and debug by end-users.
It should be clear when the ingestion is complete

Also consider SDAP data-ingest (https://github.com/unity-sds/unity-project-management/issues/143)  vs. DS file data-ingest (https://github.com/unity-sds/unity-project-management/issues/141)

**Comment by GodwinShen** [comment]
@rtapella how do we plan to accomplish this ticket?  It looks like the work-items listed in epic #141 are complete, does this give you enough to proceed with this ticket?

**Comment by rtapella** [comment]
Yes if the precursor work is done, I believe this is just a discussion with the data team to make sure they're capturing messages about the status of auto-ingest

**Comment by rtapella** [comment]
based on comments in https://github.com/unity-sds/unity-project-management/issues/141 I am going to close this.
I think we will want to be able to push errors
